services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bibliothek
      MYSQL_USER: biblio_user
      MYSQL_PASSWORD: changeme
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./bibliothek/sql/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
